In [17]:
import numpy as np

In [19]:
# find version of numpy
import numpy as np  # np is an abbreviation of numpy

print(np.__version__)
np.version.version

1.26.4


'1.26.4'

In [2]:
# Creating a 1D array  using np.array() function
array_1d = np.array([1, 2, 3, 4, 5])

# Using ndarray attributes to learn about its structure and properties

# ndarray.ndim: The number of axes (dimensions) of the array.
# ndarray.shape: The dimensions of the array, represented as a tuple.
# ndarray.size: The total number of elements in the array.
# ndarray.dtype: The data type of the elements in the array.
# ndarray.itemsize: The size in bytes of each element in the array.

print("Shape:", array_1d.shape)  # Shape: (5,)
print("each item size :", array_1d.itemsize, "bytes")   # each item size : 4 bytes
print("ndim:No. of axes/dimensions:", array_1d.ndim)  #  1
print("size:length of the array:", array_1d.size)  #  size:length of the array: 5
# observe the difference for below 2 lines
print("array_1d=",array_1d) # array_1d= [1 2 3 4 5]
array_1d   #  array([1, 2, 3, 4, 5])

Shape: (5,)
each item size : 4 bytes
ndim:No. of axes/dimensions: 1
size:length of the array: 5
array_1d= [1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [4]:
# check that a newly created object is an ndarray using type()
print(type(array_1d))  # <class 'numpy.ndarray'>
type(array_1d)

<class 'numpy.ndarray'>


numpy.ndarray

In [118]:
print(array_1d.dtype)      # int32               ----- int type takes 32/8= 4 bytes
print(array_1d.dtype.name) # int32 
array_1d.dtype             # dtype('int32')


int32
int32


dtype('int32')

In [33]:
# providing optional dtype parameter
list=[5,6,7,0,-7]
arr1d=np.array(list,dtype=bool)
arr1d

array([ True,  True,  True, False,  True])

In [119]:
array_1d.dtype.name   # 'int32'

'int32'

In [45]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(type(array_2d))  # <class 'numpy.ndarray'>
print(array_2d.dtype)  # int32
print("Shape:", array_2d.shape)  # Shape: (2,3)
print("Itemsize:(each element takes", array_2d.itemsize, "bytes )") 
 # Itemsize:(each element takes 4 bytes )
print("ndim:(No. of axes):", array_2d.ndim)  #  2
print("size:length of the array:", array_2d.size)  #  size:length of the array: 6
print("array_2d=\n",array_2d)
array_2d

<class 'numpy.ndarray'>
int32
Shape: (2, 3)
Itemsize:(each element takes 4 bytes )
ndim:(No. of axes): 2
size:length of the array: 6
array_2d=
 [[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Intrinsic Creation of Arrays
# Using Built-in Functions to create arrays with predefined values:
# np.zeros(): Creates an array filled with zeros.
# np.ones(): Creates an array filled with ones.
# np.arange(): Creates an array with a range of numbers.
# np.linspace(): Creates an array with evenly spaced numbers over a specified interval.
# np.random.rand(): Creates an array with random numbers.

# Create a 1D array of zeros
zeros1D = np.zeros((5))
print("1D array(5)filled with zeroes[using np.zeros((5)] =\n",zeros1D)

# Create a 2D array of zeros
zeros2D = np.zeros((3, 3))
print("2D array(3X3)filled with zeroes[using np.zeros((3, 3)] =\n",zeros2D)

# Create a 1D array of ones
ones1D = np.ones((5))
print("1D array(5)filled with ones [using np.ones((5))] =\n",ones1D)

# Create a 2D array of ones
ones2D = np.ones((2, 2))
print("2D array(2X2)filled with ones [using np.ones((2, 2))] =\n",ones2D)

# Create a 1D array with a range of numbers
range_array = np.arange(10)
print("1D array [using np.arange(10)] =\n",range_array)

# Create a 1D array with evenly spaced numbers
linspace_array = np.linspace(0, 1, num=5) # num default value is 50
print("array [using np.linspace(0, 1, num=5)] =\n",linspace_array)

# Create an array with random numbers
random_array = np.random.rand(2, 3)
print("2D array(2X3) [using  np.random.rand(2, 3)] =\n" ,random_array) 

1D array(5)filled with zeroes[using np.zeros((5)] =
 [0. 0. 0. 0. 0.]
2D array(3X3)filled with zeroes[using np.zeros((3, 3)] =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1D array(5)filled with ones [using np.ones((5))] =
 [1. 1. 1. 1. 1.]
2D array(2X2)filled with ones [using np.ones((2, 2))] =
 [[1. 1.]
 [1. 1.]]
1D array [using np.arange(10)] =
 [0 1 2 3 4 5 6 7 8 9]
array [using np.linspace(0, 1, num=5)] =
 [0.   0.25 0.5  0.75 1.  ]
2D array(2X3) [using  np.random.rand(2, 3)] =
 [[0.55332802 0.989349   0.86198271]
 [0.91730575 0.07773448 0.4334485 ]]


In [57]:
'''
The function np.arange() in NumPy is used to generate arrays with regularly incrementing values.
It's quite similar to Python's built-in range() function but returns an ndarray instead of a list.

numpy.arange([start, ]stop, [step, ] [dtype=None])

start: [optional] The start of the interval range. By default, it starts at 0.
stop: The end of the interval range. This number is not included in the range.
step: [optional] The spacing between two adjacent values. Default is 1.
dtype: [optional] The type of the output array. If not specified, the data type is inferred from the 
other input arguments.

'''

# Generate an array starting from 0 up to (but not including) 10.
arr = np.arange(10)  # only stop is specified, start will be 0, and step is 1
print(arr)  #  [0 1 2 3 4 5 6 7 8 9]

arr = np.arange(5, 15)  # Specifying a Start and Stop
print(arr)  #  [ 5  6  7  8  9 10 11 12 13 14]

# Using a Step: Create an array from 10 to 30, with a step of 5.
arr = np.arange(10, 30, 5)
print(arr)  # [10 15 20 25]

# Negative Step: Create a decreasing array from 10 to 0.
arr = np.arange(10, 0, -1)
print(arr)  #  [10  9  8  7  6  5  4  3  2  1]

arr = np.arange(0, 2, 0.5)  #  stpe is in float
print(arr)  #  [0.  0.5 1.  1.5]

# Specifying Data Type: Generate an array of integers from 0 to 5, 
# specifying the data type explicitly.

arr = np.arange(6, dtype=np.float32)
print(arr)  #  [0. 1. 2. 3. 4. 5.]
print(arr.dtype)  #  float32

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[10 15 20 25]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5]
[0. 1. 2. 3. 4. 5.]
float32


In [5]:
# sequences of tuples and lists interconnected make no difference.

c = np.array([[1, 2, 3],[4, 5, 6]])

d = np.array(((1, 2, 3),(4, 5, 6)))
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
f = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

print(c,"\n")
print(d,"\n")
print(e)
print(f)
f

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
g = np.array([['a', 'b'],['c', 'de']])
g                                     

array([['a', 'b'],
       ['c', 'de']], dtype='<U2')

In [67]:
g.dtype    #   dtype('<U1')
# '<U1' stands for a Unicode string with a maximum length of 1 character
# The 'U' indicates that the data type is a Unicode string.
# The 1 specifies that the string can hold a maximum of 1 character.
# The '< ' (little-endian) refers to the byte order, but for strings, 
# this isn't particularly relevant as strings are not sensitive to byte order like numeric types might be.

dtype('<U1')

In [69]:
g.dtype.name         #                  'str32'

# str: This indicates that the data type is a string.
# 32: This indicates that each string in the array can have a maximum of 32 characters.

'str32'

In [73]:
#f = np.array([[1, 2, 3],[4, 5, 6]], dtype=np.float16)
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f 

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [128]:
np.arange(4,10) 

array([4, 5, 6, 7, 8, 9])

In [129]:
np.arange(4,10,0.6)

array([4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2, 8.8, 9.4])

In [130]:
np.arange(4,16)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [131]:
np.arange(4,16,1).reshape(3,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [132]:
np.linspace(1,10,4) # third par: No. of elements into which we want the interval to be split.

array([ 1.,  4.,  7., 10.])

In [133]:
np.linspace(1,10,6) 

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [134]:
np.linspace(1,10,6).reshape(3,2)

array([[ 1. ,  2.8],
       [ 4.6,  6.4],
       [ 8.2, 10. ]])

In [81]:
# Basic Operations

a=np.arange(1,6)
print("a=", a)
# sum of an array with a scalar ( element-wise sum)
print("a+2=:", a+2)

a= [1 2 3 4 5]
a+2=: [3 4 5 6 7]


In [87]:
print("a=", a)
# product of an array with a scalar ( element-wise product)
print("a*2=:", a*2)

a= [1 2 3 4 5]
a*2=: [ 2  4  6  8 10]


In [91]:
print("a=", a)
b=np.arange(2,7)
print("b=", b)

a= [1 2 3 4 5]
b= [2 3 4 5 6]


In [93]:
# sum of an array with another array ( element-wise sum)
a+b

array([ 3,  5,  7,  9, 11])

In [141]:
a-b

array([-1, -1, -1, -1, -1])

In [173]:
print("a=", a)
print("b=",b)
print("a*b=:")
print(a*b)
print("a=", a)
print("b=",b)

a= [1 2 3 4 5]
b= [2 3 4 5 6]
a*b=:
[ 2  6 12 20 30]
a= [1 2 3 4 5]
b= [2 3 4 5 6]


In [95]:
# Universal Functions (ufunc): a function operating of an array in an element-by-element fashion. 
print("a=", a)
a*np.sin(b)

a= [1 2 3 4 5]


array([ 0.90929743,  0.28224002, -2.27040749, -3.8356971 , -1.39707749])

In [97]:
a*np.sqrt(b)

array([ 1.41421356,  3.46410162,  6.        ,  8.94427191, 12.24744871])

In [121]:
A=np.arange(0,6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
B=np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [125]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.]])

In [99]:
# The Matrix Product
A=np.arange(9).reshape(3,3)
print(A)
'''
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
'''
B=np.ones((3,3))
print(B)
'''
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
'''
print(np.dot(A,B))
'''
array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])
'''
print(np.dot(B,A)) # np.dot(B,A  is not same as np.dot(A,B); np.dot(B,A

# array([[ 9., 12., 15.],
#        [ 9., 12., 15.],
#        [ 9., 12., 15.]])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
[[ 9. 12. 15.]
 [ 9. 12. 15.]
 [ 9. 12. 15.]]


In [127]:
#  Aggregate functions: perform an operation on a set of values, an array  and produce a single result
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print("a=",a)  #array([3.3, 4.5, 1.2, 5.7, 0.3])
print("Sum=",a.sum())  #   15.0
print("Largest=",a.max())  #  5.7
print("Smallest=",a.min()) #   0.3
print("Mean=",a.mean())  #   3.0
print("Std deviation=",a.std())   # 2.0079840636817816


a= [3.3 4.5 1.2 5.7 0.3]
Sum= 15.0
Largest= 5.7
Smallest= 0.3
Mean= 3.0
Std deviation= 2.0079840636817816


In [111]:
#  Universal Functions (ufunc)
# The function that acts individually on each single element of the input array to generate a corresponding result
# in a new output array. At the end, you will obtain an array of the same size of the input.

B=np.arange(1,5)
print("B=",B)  #  B= [ 1 2 3 4]
print(np.sqrt(B)) #
print(np.sin(B)) #  array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])
print(np.log(B)) # array([0.        , 0.69314718, 1.09861229, 1.38629436])
# log base e

B= [1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [303]:
# Increment and Decrement Operators

a = np.arange(4) 
print("a=\n",a)   # array([0, 1, 2, 3])
a += 1  
print("a after (a += 1)  =\n",a)  # array([1, 2, 3, 4])
a -= 1  
print("a after (a -= 1)=\n",a)    # array([0, 1, 2, 3])

a=
 [0 1 2 3]
a after (a += 1)  =
 [1 2 3 4]
a after (a -= 1)=
 [0 1 2 3]


In [357]:
#  Increment and Decrement Operators: more examples
a=np.array([0, 1, 2, 3])
a += 4
print("a=\n",a)  # array([4, 5, 6, 7])
a *= 2 
print("a=\n",a) #  array([ 8, 10, 12, 14])  

a=
 [4 5 6 7]
a=
 [ 8 10 12 14]


In [191]:
import numpy as np

# Creating an array with an integer, a float, and a string
mixed_array = np.array([1, 3.14, 'hello'])

print(mixed_array)  # ['1' '3.14' 'hello'] -- All elements in mixed_array are converted to strings
print("Data type of the array:", mixed_array.dtype) # Data type of the array: <U32
print("itemsize=", mixed_array.itemsize)  # 128 
# <U32: This dtype indicates that the array is of Unicode strings (string type in NumPy), 
# with a maximum length of 32 characters for each element.
# All elements in mixed_array are converted to strings. The numbers 1 and 3.14 are stored as '1' and '3.14', 
# respectively, so they can coexist with the string 'hello' in the same array. 
# Disadvantages:
# 1)Loss of Numeric Operations:
# 2) Memory and Performance:  Using strings can use more memory


['1' '3.14' 'hello']
Data type of the array: <U32
itemsize= 128


In [143]:
#  Indexing, Slicing, and Iterating
a= np.arange(10,16)
print("a=",a)     #    a= [10 11 12 13 14 15]
# positive indexing
print("a[3]=",a[3]) #   a[3]=13
# negetive indexing
print("a[-3]=",a[-3]) #   a[-3]=13

a=np.arange(10,14).reshape(2,2)  
print("a=",a)
#        array([[10, 11],
#              [12, 13]])
print("a[1][0]=",a[1,0])   # element in row 1, col 0 i.e., a[1][0]  ----  a[1][0]= 12



a= [10 11 12 13 14 15]
a[3]= 13
a[-3]= 13
a= [[10 11]
 [12 13]]
a[1][0]= 12


In [141]:
# To select multiple items at once, you can pass array of indexes within the square brackets.
a= np.arange(10,16)
print("a=",a)     #    a= [10 11 12 13 14 15]
print("a[[1,4,5]]=", end=' ') 
print(a[[1,4,5]]) # select elements at indexes 1,4 and 5
a[[1,4,5]] #  [[1,4,5]]= [11 14 15]

a= [10 11 12 13 14 15]
a[[1,4,5]]= [11 14 15]


array([11, 14, 15])

In [195]:
# Slicing:  allows you to extract portions of an array to generate new ones.
arr= np.arange(10,16) #  array([10, 11, 12, 13, 14, 15])
print("arr=",arr)
print("arr[1:5]=",arr[1:5]) # array([11, 12, 13, 14])
print("arr[1:5:2]=",arr[1:5:2]) # array([11, 13])
print("arr[:5:2]=",arr[:5:2]) # array([10, 12, 14])
print("arr[:5:]=", arr[:5:]) # array([10, 11, 12, 13, 14])
print("arr[::2]=",arr[::2])  # array([10, 12, 14]) 

arr= [10 11 12 13 14 15]
arr[1:5]= [11 12 13 14]
arr[1:5:2]= [11 13]
arr[:5:2]= [10 12 14]
arr[:5:]= [10 11 12 13 14]
arr[::2]= [10 12 14]


In [207]:
A=np.arange(10,19).reshape(3,3)
print("A=", A)

'''array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])
'''
print("A[1,:]_________")  # 1, Selects the row 1 of the array.
                           #  : or :: Selects all columns.
print(A[1,::] ) #  Accessing a row      ----  array([13, 14, 15])

print("A[:,2]__________") # all rows, but col 2
print(A[:,2])   #   Accessing a column -----array([12, 15, 18])

print("A[0:1,1:2]__________") # same as A[0,1]
print(A[0:1,1:2])  # array([[11]])

print("A[0:2,1:2]__________")
print(A[0:2,1:2] ) 

# ''' array([[11],
#           [14]])
# '''  
print("A[[0,2],1:2]__________") # rows 0 and 2   , col 1
print(A[[0,2],1:2] )            
# '''array([[11],
#        [17]])
# '''

A= [[10 11 12]
 [13 14 15]
 [16 17 18]]
A[1,:]_________
[13 14 15]
A[:,2]__________
[12 15 18]
A[0:1,1:2]__________
[[11]]
A[0:2,1:2]__________
[[11]
 [14]]
A[[0,2],1:2]__________
[[11]
 [17]]


In [211]:
# Iterating an Array
print('ndarray display')  
print(A)
print('\n')    

# make an iteration row by row
print('row by row display')   
for row in A:  # A is 2D ndarray object
    print(row)
print('\n')    

# [10 11 12]
# [13 14 15]
# [16 17 18]
# make an iteration element by element, use A.flat
print('element by element display')  

for item in A.flat:
    print(item, end=" ") # 10 11 12 13 14 15 16 17 18 

ndarray display
[[10 11 12]
 [13 14 15]
 [16 17 18]]


row by row display
[10 11 12]
[13 14 15]
[16 17 18]


element by element display
10 11 12 13 14 15 16 17 18 

In [249]:
# np.apply_along_axis(np.sum,axis=0,arr=A) 
# This function takes three arguments: the aggregate function, the axis on which to apply the iteration,and array. 

A=np.arange(10,19).reshape(3,3)
print("A=",A)
'''
A= [[10 11 12]
 [13 14 15]
 [16 17 18]]
 
'''
print("______") # column sum
print(np.apply_along_axis(np.sum,axis=0,arr=A) ) #array([39, 42, 45])

print("______") # row sum
print(np.apply_along_axis(np.sum,axis=1,arr=A)) #array([33, 42, 51])

def foo(x):    # x receives column when axis=0
    print ("column ", x ,"\n")
    return x/2

def foo1(x): # x receives row when axis=1
    print ("row ",x ,"\n")
    return 2*x
    
print("______")
print(np.apply_along_axis(foo,axis=0,arr=A))

print("______")
# array([[5. , 5.5, 6. ],
#        [6.5, 7. , 7.5],
#        [8. , 8.5, 9. ]])
print(np.apply_along_axis(foo1,axis=1,arr=A))


A= [[10 11 12]
 [13 14 15]
 [16 17 18]]
______
[39 42 45]
______
[33 42 51]
______
column  [10 13 16] 

column  [11 14 17] 

column  [12 15 18] 

[[5.  5.5 6. ]
 [6.5 7.  7.5]
 [8.  8.5 9. ]]
______
row  [10 11 12] 

row  [13 14 15] 

row  [16 17 18] 

[[20 22 24]
 [26 28 30]
 [32 34 36]]


In [377]:
# Conditions and Boolean Arrays

B= np.random.random((3,3))
print("B=",B)
'''array([[0.32174415, 0.90265544, 0.34943847],
       [0.45981683, 0.44257697, 0.13372979],
       [0.69003583, 0.68330169, 0.47230614]]) '''
print(B>0.5)
'''array([[False,  True, False],
       [False, False, False],
       [ True,  True, False]]) '''
B[B>0.5]

#array([0.90265544, 0.69003583, 0.68330169])


B= [[7.91774568e-01 2.66178369e-01 6.04277963e-05]
 [5.20671403e-01 5.12535568e-01 8.07761546e-01]
 [5.95682983e-01 7.34707789e-01 7.49405495e-01]]
[[ True False False]
 [ True  True  True]
 [ True  True  True]]


array([0.79177457, 0.5206714 , 0.51253557, 0.80776155, 0.59568298,
       0.73470779, 0.74940549])

In [13]:
# Shape Manipulation

a= np.arange(6)
print("a=", a)    # [0.68834651, 0.78617408, 0.56955739, 0.04060049, 0.55295284,  0.44824633]
A=a.reshape(2,3) # Change the shape of an array without changing its data
print("Reshaped array: A=a.reshape(2,3)=\n", A)   #   array([[0.68834651, 0.78617408, 0.56955739],
                                                     #  [0.04060049, 0.55295284, 0.44824633]])
print("The transpose of A:")
print(A.transpose() )
# array([[0.68834651, 0.04060049],
#        [0.78617408, 0.55295284],
#        [0.56955739, 0.44824633]])

print("The value of a.shape is \n", a.shape)
# To modify the object by modifying the shape, assign a tuple containing the new dimensions directly to its shape attribute.
a.shape=(2,3)
print("After executing a.shape=(2,3), a.shape=\n", a.shape)
print("After reshape:a=\n", a)

# ravel(): To convert a two-dimensional array into a one-dimensional array,
a1D=a.ravel()   # array([0.68834651, 0.78617408, 0.56955739, 0.04060049, 0.55295284,  0.44824633])
print("After converting 2D array to 1D array using a1D=a.ravel() : ",a1D)



a= [0 1 2 3 4 5]
Reshaped array: A=a.reshape(2,3)=
 [[0 1 2]
 [3 4 5]]
The transpose of A:
[[0 3]
 [1 4]
 [2 5]]
The value of a.shape is 
 (6,)
After executing a.shape=(2,3), a.shape=
 (2, 3)
After reshape:a=
 [[0 1 2]
 [3 4 5]]
After converting 2D array to 1D array using a1D=a.ravel() :  [0 1 2 3 4 5]


In [253]:
# Array Manipulation

a=np.ones((2,2)) # by default the dtype is float64
print(a.dtype)
print("a=\n", a,"\n")
# array([[1., 1.],
#        [1., 1.]])
b=np.zeros((2,2))
print("b=\n",b,"\n")
# array([[0., 0.],
#        [0., 0.]])
print("np.vstack((a,b))=\n",np.vstack((a,b)),"\n")
# array([[1., 1.],
#        [1., 1.],
#        [0., 0.],
#        [0., 0.]])
print("np.hstack((a,b))=\n",np.hstack((a,b)),"\n")
# array([[1., 1., 0., 0.],
#        [1., 1., 0., 0.]])

a=np.array((1,2,3))
b=np.array((4,5,6))
print("a=\n", a,"\n")
print("b=\n", b,"\n")
print("np.column_stack(a,b)\n")
np.column_stack((a,b))
# array([[1, 4],
#        [2, 5],
#        [3, 6]])




float64
a=
 [[1. 1.]
 [1. 1.]] 

b=
 [[0. 0.]
 [0. 0.]] 

np.vstack((a,b))=
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]] 

np.hstack((a,b))=
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]] 

a=
 [1 2 3] 

b=
 [4 5 6] 

np.column_stack(a,b)



array([[1, 4],
       [2, 5],
       [3, 6]])

In [249]:
print("np.row_stack((a,b)\n")
np.row_stack((a,b))
# array([[1, 2, 3],
#        [4, 5, 6]])

np.row_stack((a,b)



array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
# Splitting Arrays

A=np.arange(16).reshape(4,4)
print("A=\n",A)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15]])

[B,C]=np.hsplit(A,2)
print("\nAfter np.hsplit(A,2)")
print("B=\n",B)
# array([[ 0,  1],
#        [ 4,  5],
#        [ 8,  9],
#        [12, 13]])
print("C=\n",C)
# array([[ 2,  3],
#        [ 6,  7],
#        [10, 11],
#        [14, 15]])

print("\nAfter np.vsplit(A,2)")
[B,C]=np.vsplit(A,2)
print("B=\n",B)
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
print("C=\n",B)
# array([[ 8,  9, 10, 11],
#        [12, 13, 14, 15]])

A=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After np.hsplit(A,2)
B=
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
C=
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

After np.vsplit(A,2)
B=
 [[0 1 2 3]
 [4 5 6 7]]
C=
 [[0 1 2 3]
 [4 5 6 7]]


In [261]:
print(A)
# split() function allows to split the array into nonsymmetrical parts

#  splits the matrix A along columns (because axis=1).

[A1,A2,A3] = np.split(A,[1,3],axis=1)

The list [1, 3] indicates the split points:
First split after the 1st column.
Second split after the 3rd column

print("A1=\n",A1)

# array([[ 0],
#        [ 4],
#        [ 8],
#        [12]])
print("A2=\n",A2)
# array([[ 1,  2],
#        [ 5,  6],
#        [ 9, 10],
#        [13, 14]])
print("A3=\n",A3)
# array([[ 3],
#        [ 7],
#        [11],
#        [15]])
[A1,A2,A3] = np.split(A,[1,3],axis=0)
print("A1=\n",A1)
         # array([[0, 1, 2, 3]])
print("A2=\n",A2)
        # array([[ 4,  5,  6,  7],
           #    [ 8,  9, 10, 11]])
print("A3=\n",A3)     # array([[12, 13, 14, 15]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
A1=
 [[ 0]
 [ 4]
 [ 8]
 [12]]
A2=
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
A3=
 [[ 3]
 [ 7]
 [11]
 [15]]
A1=
 [[0 1 2 3]]
A2=
 [[ 4  5  6  7]
 [ 8  9 10 11]]
A3=
 [[12 13 14 15]]


In [263]:
#  General Concepts

a=np.array([1,2,3,4])
print("a=\n",a)
b=a
a[1]=5
print("b=\n",b)  # array([1, 5, 3, 4])
# to generate a complete copy and distinct array you can use the copy() function
c=a.copy()
print("c=\n",c)   # array([1, 5, 3, 4])
a[1]=78
print("a=\n",a) # array([ 1, 78,  3,  4])
print("c=\n",c)   # array([1, 5, 3, 4])

a=
 [1 2 3 4]
b=
 [1 5 3 4]
c=
 [1 5 3 4]
a=
 [ 1 78  3  4]
c=
 [1 5 3 4]


In [271]:
# Vectorization
# The vectorization is the absence of explicit loop during the developing of the code.

# multiplication of two arrays:
# c= a * b
# In other languages
# for (i = 0; i < rows; i++){
# c[i] = a[i]*b[i];
# }
# or even two matrices:
# C=A * B
# In other languages, While the product of matrices would be expressed as follows:
# for( i=0; i < rows; i++){
# for(j=0; j < columns; j++){
# c[i][j] = a[i][j]*b[i][j];
# }
# }


a=np.array([[1,2,3,4],[1,2,3,4]])
print("a=\n",a)  
# array([[1, 2, 3, 4],
#        [1, 2, 3, 4]])
      
b=np.array([[1,1,1,1],[2,2,2,2]])
print("b=\n",b)  
print("\na*b=\n",a*b)  
# array([[1, 2, 3, 4],
#        [2, 4, 6, 8]])


a=
 [[1 2 3 4]
 [1 2 3 4]]
b=
 [[1 1 1 1]
 [2 2 2 2]]

a*b=
 [[1 2 3 4]
 [2 4 6 8]]


In [255]:
# Broadcasting is the operation that allows an operator or a function to act on two or more 
# arrays to operate even if these arrays do not have exactly the same shape.
# Two arrays may be subjected to broadcasting when all their dimensions are compatible, i.e., the length of each
# dimension must be equal between the two arrays or one of them must be equal to 1. 
# If thesetwo conditions are not met, you get an exception given that the two arrays are not compatible

A=np.arange(16).reshape((4,4))
print("A=\n",A)   # 2D array

# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15]])

B=np.arange(4)   # 1D array
print("B=\n",B,"\n")   # array([0, 1, 2, 3])   

print("A+B=\n" ,A+B)
# array([[ 0,  2,  4,  6],
#        [ 4,  6,  8, 10],
#        [ 8, 10, 12, 14],
#        [12, 14, 16, 18]])

A=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
B=
 [0 1 2 3] 

A+B=
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]


In [9]:
# Structured Arrays in Python (using NumPy)
# allow you to create arrays that can hold different types of data in each field,
# similar to a database table where each column can have a different data type.
# This is useful when working with heterogeneous data (data of mixed types) like records or tables, 
# where each row may represent an entity with attributes of various types.

# Bytes: b1  , int:  i1, i2, i4, i8, unsigned ints:  u1, u2, u4, u8, floats: f2, f4, f8, 
# complex:  c8, c16, fixed length strings: a<n>
import numpy as np
struct1= np.array([(1,'first',0.56,1+2j),(2,'second',0.66,3+4j),(3,'third',0.76,5+6j)],dtype=('i2,a6,f4,c8'))

print("struct1=\n", struct1)
                                                                                              
# array([(1, b'first', 0.56, 1.+2.j), (2, b'second', 0.78, 3.+4.j)],
#       dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])
# names are assigned automatically with an f field, can be specified with suitable names
                                                                                              
struct1


struct1=
 [(1, b'first', 0.56, 1.+2.j) (2, b'second', 0.66, 3.+4.j)
 (3, b'third', 0.76, 5.+6.j)]


array([(1, b'first', 0.56, 1.+2.j), (2, b'second', 0.66, 3.+4.j),
       (3, b'third', 0.76, 5.+6.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [73]:
print("struct1[1]=\n", struct1[1])  #  Display a record:     
struct1['f3'] # Display a column: 

struct1[1]=
 (2, b'second', 0.66, 3.+4.j)


array([1.+2.j, 3.+4.j, 5.+6.j], dtype=complex64)

In [65]:
structured = np.array([(1,'First',0.50,1+2j),(2,'Second',0.6,2-2j),(3,'Third',0.7,1+3j)],
dtype=[('id','i2'),('order','a6'),('value','f4'),('complex','c8')])
structured 

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 0.6, 2.-2.j),
       (3, b'Third', 0.7, 1.+3.j)],
      dtype=[('id', '<i2'), ('order', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [71]:
structured['value'] 

array([0.5, 0.6, 0.7], dtype=float32)

In [69]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 0.6, 2.-2.j),
       (3, b'Third', 0.7, 1.+3.j)],
      dtype=[('id', '<i2'), ('order', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [43]:
# Reading and Writing Array Data on Files
data=np.random.rand(4,3)
print(data)
np.save('saved_data',data)
loaded_data = np.load('saved_data.npy')
loaded_data

[[0.52511383 0.91381322 0.48423581]
 [0.94904987 0.71941215 0.15307693]
 [0.94409069 0.48108344 0.72419119]
 [0.62369894 0.18360464 0.43708171]]


array([[0.52511383, 0.91381322, 0.48423581],
       [0.94904987, 0.71941215, 0.15307693],
       [0.94409069, 0.48108344, 0.72419119],
       [0.62369894, 0.18360464, 0.43708171]])

In [13]:
# Reading File with Tabular Data

# sample.csv file contents

# id,value1,value2,value3
# 1,123,1.4,23
# 2,110,9.5,18
# 3,4,2.1,19

# bytes b1   # int i1, i2, i4, i8  # unsigned ints u1, u2, u4, u8   # floats f2, f4, f8   # complex c8, c16  # fixed length strings a<n>

data = np.genfromtxt('sample.csv', delimiter=',', names=True, dtype=('i2','i4','f4','i2'))
# names=true
print("data['id']=",data['id'])   # display id column
print("data[0]=",data[0])    # display row 0
print("data[1]=",data[1])     # dipslay row 1
print("data=")
data   # observe column names below the array along with their types

data['id']= [1 2 3]
data[0]= (1, 123, 1.4, 23)
data[1]= (2, 110, 0.5, 18)
data=


array([(1, 123, 1.4, 23), (2, 110, 0.5, 18), (3, 164, 2.1, 19)],
      dtype=[('id', '<i2'), ('value1', '<i4'), ('value2', '<f4'), ('value3', '<i2')])

In [299]:
# Observe some values are removed
# sample2.csv file contents
# id,value1,value2,value3
# 1,123,1.4,23
# 2,110,,18
# 3,,2.1,19

data2 = np.genfromtxt('sample2.csv', delimiter=',', names=True)
print("data2.dtype=",data2.dtype, "\n")
data2

data2.dtype= [('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')] 



array([(1., 123., 1.4, 23.), (2., 110., nan, 18.), (3.,  nan, 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [261]:
data=(1,2,3,4,5.6,6.7,8,9,'str')
print("data=\n",data)
# (1, 2, 3, 4, 5.6, 6.7, 8, 9, 'str')
np.save('F1',data)
F2=np.load('F1.npy')
F2  #  array(['1', '2', '3', '4', '5.6', '6.7', '8', '9', 'str'], dtype='<U32')


data=
 (1, 2, 3, 4, 5.6, 6.7, 8, 9, 'str')


array(['1', '2', '3', '4', '5.6', '6.7', '8', '9', 'str'], dtype='<U32')

In [183]:
# The np.linspace function in NumPy is used to generate evenly spaced numbers over a specified interval.
# It is particularly useful for creating sequences of numbers when you know the start and end points and want to 
# specify the number of samples you need within that range.

# Common Use Cases
# Plotting Functions: Often used in generating x-values for plotting functions over a range.
# Creating Grids: Useful for creating grids of points in numerical simulations.
# Sampling: Handy for sampling points from a continuous function or distribution.

# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# start: The starting value of the sequence.
# stop: The end value of the sequence.
# num (optional): The number of samples to generate. The default is 50.
# endpoint (optional): If True (the default), stop is the last value in the sequence.
                    #  If False, the sequence will end before stop.
# retstep (optional): If True, return the step size along with the samples.
# dtype (optional): The data type of the output array.
# axis (optional): The axis in the result along which the linspace samples are stored. The default is 0.

result = np.linspace(0, 1, num=5, retstep=True)
print(result) #   (array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25) 
# start=0: The sequence starts at 0.
# stop=1: The sequence ends at 1.
# num=5: There are 5 samples generated between 0 and 1, inclusive.
# Even Spacing: The numbers generated are evenly spaced within the interval [0, 1]. 
# The spacing, in this case, is 0.25.

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)


In [191]:

result, step = np.linspace(0, 2, num=8, endpoint=False, retstep=True) 
# default is True for endpoint ( indicates that stop(2) is the end value in the sequence)
# if endpoint is False, the sequence will end before stop
# retstep default value is False
print("Result:", result)
print("Step size:", step)


Result: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75]
Step size: 0.25


In [231]:
import numpy as np
arr= np.array(((1,2,5),(1,2,"5.6asdfgh67"))) # max length is 11 chars , so size is 4*11=44
print("Total No. of elements=",arr.size)# Total No. of elements= 6
print("Each item size in bytes=",arr.itemsize)# Each item size in bytes= 44
print(arr.dtype,"    ", arr.dtype.name) # 352/8=44

Total No. of elements= 6
Each item size in bytes= 44
<U11      str352


In [47]:
import numpy as np
# Creating an array with an integer, a float, and a boolean
mixed_array = np.array([1, 3.14, True])  # The boolean True is treated as 1.0 and False as 0.0 when upcast to floats.
# bool to float conversion happens as there is le
print(mixed_array)
print("Data type of the array:", mixed_array.dtype)


[1.   3.14 1.  ]
Data type of the array: float64


In [79]:
import numpy as np

# Define the data types for each attribute
book_dtype = [
    ('title', 'S50'),        # Title of the book (up to 50 characters)
    ('ISBN', 'S13'),         # ISBN number (13 characters)
    ('author', 'S30'),       # Author of the book (up to 30 characters)
    ('year', 'i4'),          # Year of publication (integer)
    ('available_copies', 'i4')  # Number of available copies (integer)
]

# Create an array of library books
library_records = np.array([
    ('Introduction to Algorithms', '9780262033848', 'Thomas H. Cormen', 2009, 5),
    ('Clean Code', '9780132350884', 'Robert C. Martin', 2008, 2),
    ('Design Patterns', '9780201633610', 'Erich Gamma', 1994, 3),
    ('Artificial Intelligence', '9780136042594', 'Stuart Russell', 2010, 4),
    ('The Pragmatic Programmer', '9780201616224', 'Andrew Hunt', 1999, 6)
], dtype=book_dtype)

# Access and display the full records
print("Library Records:")
print(library_records)

# Access specific fields (e.g., Titles and Authors)
print("\nBook Titles:", library_records['title'])
print("Authors:", library_records['author'])

# Filter books published after 2000
books_after_2000 = library_records[library_records['year'] > 2000]
print("\nBooks published after 2000:")
print(books_after_2000)

# Sort by available copies
sorted_by_copies = np.sort(library_records, order='available_copies')
print("\nSorted by available copies:")
print(sorted_by_copies)

# Sort by title
sorted_by_title = np.sort(library_records, order='title')
print("\nSorted by title:")
print(sorted_by_title)

Library Records:
[(b'Introduction to Algorithms', b'9780262033848', b'Thomas H. Cormen', 2009, 5)
 (b'Clean Code', b'9780132350884', b'Robert C. Martin', 2008, 2)
 (b'Design Patterns', b'9780201633610', b'Erich Gamma', 1994, 3)
 (b'Artificial Intelligence', b'9780136042594', b'Stuart Russell', 2010, 4)
 (b'The Pragmatic Programmer', b'9780201616224', b'Andrew Hunt', 1999, 6)]

Book Titles: [b'Introduction to Algorithms' b'Clean Code' b'Design Patterns'
 b'Artificial Intelligence' b'The Pragmatic Programmer']
Authors: [b'Thomas H. Cormen' b'Robert C. Martin' b'Erich Gamma' b'Stuart Russell'
 b'Andrew Hunt']

Books published after 2000:
[(b'Introduction to Algorithms', b'9780262033848', b'Thomas H. Cormen', 2009, 5)
 (b'Clean Code', b'9780132350884', b'Robert C. Martin', 2008, 2)
 (b'Artificial Intelligence', b'9780136042594', b'Stuart Russell', 2010, 4)]

Sorted by available copies:
[(b'Clean Code', b'9780132350884', b'Robert C. Martin', 2008, 2)
 (b'Design Patterns', b'9780201633610', 